### ISSUE TITLE
💪 glasto! Whoop whoop

### ISSUE THREAD

**Issue by export-mike** [thomasms/glastoselenium#1]
Yo!

Any idea what you’ll be using to look for to stop the refresh? I see your examples just check for google.

**Comment by eddieod88** [comment]
> Yo!
> 
> Any idea what you’ll be using to look for to stop the refresh? I see your examples just check for google.

In the glasto2019.original.py file, it looks like he continually refreshes until he does NOT see a string from the PHRASES_TO_CHECK array in the innerHTML of the refreshed webpage. These strings  could potentially be different this year though, so they may have to change... maybe not though. Its a bit of a guessing game I suppose. 

Any other thoughts as to how to improve this??

**Comment by thomasms** [comment]
Yes indeed, it is quite crude but it worked well last year. The phrases to check may be different, but did not change much from the previous time. It is impossible to tell until the day of the sale.

The good news is that they do a Thursday coach sale, and I usually use this to check the site. Most development will happen here between this Thursday and Saturday, ready for the sale on Sunday. No one wants to travel by coach.

**Comment by eddieod88** [comment]
Ok great. Good shout. 

And by 'worked well', do you mean that you managed to get tickets and not get banned from Glastonbury??

**Comment by thomasms** [comment]
Yes, I have managed to get tickets every year with this script. I do source this script out to many different machines on many different locations though. One instance is not enough.

They cannot detect this automation, the volume is too high to the site for them to detect anything.

The whole system is unfair. If everyone uses bots or scripts like this then (hopefully) it should force them to change their ticket sale model.

**Comment by cameronepstein** [comment]
What do you use to source the script out? 

And are you saying the volume is too high for them to detect it from a single instance? 

That's interesting if so. Would've thought they'd just block any ip's making < $X requests per minute....

**Comment by chrisgilbert** [comment]
Thanks for this script. Going to take a look tonight. You can use selenium grid to run from multiple agents at once. From the last couple of years it doesn’t look like they block IPs so much as rate limit them. Otherwise people hitting F5 repeatedly would get blocked too. They’ve basically designed a system in which success is entirely derived from how fast you can hit their servers, and put your details in. 

Their cookies site says they use the sclid cookie for rate limiting. 

The X-Mapping-kgibjjhc is set to a hash of the backend server and used for sticky sessions. It’s created by Stingray Traffic Manager. I think should have several distinct values which represent each of the web servers, and after discovering them you could probably set the cookie and route requests to a particular web server. Probably would want to stay on the same server once you got in the queue though.

https://glastonbury.seetickets.com/content/cookies-info

**Comment by thomasms** [comment]
Great, thanks for sharing. I didn't know about Selenium grid, I will have a look.

Indeed, if they started blocking refresh rate everyone would get blocked.

My way of creating multiple instances was to fire up a few VMs in various locations, and run the script there - not very rigorous, nor clever, but it helps. Also creating many different instances locally helps.

Of course, pull requests are always welcome!

**Comment by thomasms** [comment]
I presume you have also heard of the Refreshinator - https://refreshinator.com/index.html.

They advise against it apparently. 
https://www.theticketingbusiness.com/2017/04/20/glastonbury-warn-refreshinator-crash/

**Comment by chrisgilbert** [comment]
I had a go with check4change plugin this evening with no luck getting past the first holding page. I noticed it was loading google anayltics and translate objects, and I ended up getting blocked by google. I was on a VPN at the time, so didn't really cause me a big problem.

It might have been leaving the ignore cache settings turned on in dev tools for a couple of minutes, or it might be that they didn't like all the analytics traffic. Either way I am going to block all that stuff on Sunday.

They are warning against auto-refresh software to allow "everyone a fair chance to get tickets." Presumably only those are able bodied enough to hit refresh over and over for an hour though!

There's so many other ways they could do it - a FIFO queue, a lottery, etc. I think the idea that the system of refreshing and hoping is fair is pretty silly.
